### ISSUE TITLE
Integrate my-neural-network as a model

### ISSUE THREAD

**Issue by DeepBlockDeepak** [DeepBlockDeepak/kaggle_titanic#24]
##  Description
Integrate the `my-neural-network` project as a dependency into this project. Leverage the `SimpleNeuralNetwork` and `ActivationFunction` classes from `my-neural-network` for modeling.

## Tasks:

- [ ] Add my-neural-network as a dependency in pyproject.toml via the project's Git repository.
- [ ] Install the new dependency using Poetry and make sure the environment correctly sets up.
- [ ] Write a basic test to verify that the imported modules work correctly within the kaggle_titanic.
